import Head from 'next/head'
import Collections from "../components/Collections";
import Subscriptions from "../components/Subscriptions";
import NewArrivals from "../components/NewArrivals";

export default function Home() {

  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NewArrivals />
        <Collections />
        <Subscriptions />
      </div>
    </div>
  )
}